"""
Collect identifying strings from local, untracked statements into
.git/info/sensitive-strings, which the privacy check blocks from commits.

    cd backend && uv run python scripts/refresh_sensitive_strings.py

Scans every PDF under sample_data/ that git does not track (i.e. real,
gitignored statements), using sample_data/.pdf_password when needed, and
records: account numbers, holder-name words, email addresses and long digit
runs (customer IDs, phone numbers) from the first pages. Lines you add by
hand below the "# manual" marker are kept. Values are never printed.
"""
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]          # repository root

from bank_parser.extraction.lines import page_text      # noqa: E402
from bank_parser.extraction.unknown import extract_unknown  # noqa: E402
from bank_parser.pdf import PdfError, open_pdf            # noqa: E402

OUT = ROOT / ".git" / "info" / "sensitive-strings"
HONORIFICS = {"mr", "mrs", "ms", "miss", "dr", "m/s", "shri", "smt"}
EMAIL_RE = re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}")
DIGITS_RE = re.compile(r"\b\d{9,18}\b")


def untracked_pdfs():
    tracked = set(subprocess.run(["git", "ls-files", "sample_data"], cwd=ROOT, capture_output=True,
                                 text=True, check=True).stdout.split())
    return [p for p in sorted((ROOT / "sample_data").glob("*.pdf"))
            if p.relative_to(ROOT).as_posix() not in tracked]


def collect(path, password):
    found = set()
    with open_pdf(path, password) as doc:
        text = "\n".join(page_text(doc.page(n)) for n in range(1, min(doc.page_count, 2) + 1))
        result, _ = extract_unknown(doc, path, password)
    found.update(m.group(0) for m in EMAIL_RE.finditer(text))
    found.update(DIGITS_RE.findall(text))
    if result.statement is not None:
        h = result.statement.header
        if h.account_number:
            found.add(h.account_number)
        for word in re.split(r"[\s.,]+", h.account_holder_name or ""):
            if len(word) >= 4 and word.lower() not in HONORIFICS:
                found.add(word)
    return found


def main():
    pw_file = ROOT / "sample_data" / ".pdf_password"
    password = pw_file.read_text(encoding="utf-8").strip() if pw_file.exists() else None
    manual = []
    if OUT.exists():
        lines = OUT.read_text(encoding="utf-8").splitlines()
        if "# manual" in lines:
            manual = lines[lines.index("# manual") + 1:]
    found, scanned = set(), 0
    for pdf in untracked_pdfs():
        for pw in (None, password):
            try:
                found |= collect(pdf, pw)
                scanned += 1
                break
            except PdfError:
                continue
    OUT.parent.mkdir(parents=True, exist_ok=True)
    body = ["# Generated by scripts/refresh_sensitive_strings.py -- local only, never committed.",
            *sorted(found), "# manual", *manual]
    OUT.write_text("\n".join(body) + "\n", encoding="utf-8")
    print(f"scanned {scanned} local statement(s); {len(found)} generated + {len(manual)} manual entries "
          f"written to .git/info/sensitive-strings")


if __name__ == "__main__":
    main()
